// Phase 12g — one-time backfill of stories.generic_commentary and
// events.generic_commentary for rows that landed before migration 0030.
//
// Strategy: derive the role-neutral text from existing data on each
// row rather than calling Haiku. The accessible-depth variant in
// why_it_matters_template is exactly what we want — role-neutral, plain-
// English, pre-generated by the earlier 12a regeneration pass or the
// 12e.5b tier-generation seam. The two tables carry slightly different
// template shapes:
//   - stories.why_it_matters_template uses the 12a per-tier-string shape
//     ({accessible: string, briefed: string, technical: string}). For
//     these rows, generic_commentary = template.accessible verbatim.
//   - events.why_it_matters_template uses the 12e.5b per-tier
//     {thesis, support} shape. For these rows,
//     generic_commentary = accessible.thesis + " " + accessible.support.
//
// Fallback chain when the template is null / malformed / missing the
// accessible key: write `why_it_matters` directly. The read-side path
// already falls back to why_it_matters when the column is null, so
// this script is purely a latency optimization — it spares the
// per-request fallback for every row it touches.
//
// Idempotency: only touches rows where generic_commentary IS NULL.
// Re-runs are safe; running mid-deploy can't double-update.
//
// CLI:
//   npm run backfill-generic-commentary
//   npm run backfill-generic-commentary -- --dry-run
//   npm run backfill-generic-commentary -- --table=stories
//   npm run backfill-generic-commentary -- --table=events

import "../lib/loadEnv";
import { and, eq, isNull, sql } from "drizzle-orm";

import { db } from "../db";
import { events, stories } from "../db/schema";
import {
  parseTierTemplate,
  parseWhyItMattersTemplate,
} from "../utils/depthVariants";

interface Args {
  dryRun: boolean;
  table: "stories" | "events" | "both";
}

function parseArgs(argv: readonly string[]): Args {
  const dryRun = argv.includes("--dry-run");
  let table: Args["table"] = "both";
  for (const arg of argv) {
    if (arg === "--table=stories") table = "stories";
    else if (arg === "--table=events") table = "events";
    else if (arg === "--table=both") table = "both";
  }
  return { dryRun, table };
}

/**
 * Derive the role-neutral commentary text for a stories row. Returns
 * null if neither the template nor the why_it_matters yields a non-
 * empty string (shouldn't happen in practice — why_it_matters is NOT
 * NULL on stories — but the typing is defensive).
 */
export function deriveStoryGenericCommentary(
  whyItMatters: string,
  whyItMattersTemplate: string | null,
): string | null {
  const tpl = parseWhyItMattersTemplate(whyItMattersTemplate);
  if (tpl) {
    const accessible = tpl.accessible.trim();
    if (accessible.length > 0) return accessible;
  }
  const fallback = whyItMatters.trim();
  return fallback.length > 0 ? fallback : null;
}

/**
 * Derive the role-neutral commentary text for an events row. The 12e.5b
 * template shape carries {thesis, support} per tier; we concatenate
 * both on the accessible tier so the text reads as a full paragraph.
 */
export function deriveEventGenericCommentary(
  whyItMatters: string,
  whyItMattersTemplate: string | null,
): string | null {
  const tpl = parseTierTemplate(whyItMattersTemplate);
  if (tpl) {
    const parts = [tpl.accessible.thesis, tpl.accessible.support]
      .map((s) => s.trim())
      .filter((s) => s.length > 0);
    if (parts.length > 0) return parts.join(" ");
  }
  const fallback = whyItMatters.trim();
  return fallback.length > 0 ? fallback : null;
}

interface BackfillStats {
  scanned: number;
  updated: number;
  fellBack: number; // used why_it_matters fallback (template not usable)
}

async function backfillStories(dryRun: boolean): Promise<BackfillStats> {
  const stats: BackfillStats = { scanned: 0, updated: 0, fellBack: 0 };
  const rows = await db
    .select({
      id: stories.id,
      whyItMatters: stories.whyItMatters,
      whyItMattersTemplate: stories.whyItMattersTemplate,
    })
    .from(stories)
    .where(isNull(stories.genericCommentary));
  for (const row of rows) {
    stats.scanned += 1;
    const derived = deriveStoryGenericCommentary(
      row.whyItMatters,
      row.whyItMattersTemplate,
    );
    if (!derived) continue;
    const usedFallback = !parseWhyItMattersTemplate(row.whyItMattersTemplate);
    if (usedFallback) stats.fellBack += 1;
    if (!dryRun) {
      await db
        .update(stories)
        .set({ genericCommentary: derived })
        .where(
          and(eq(stories.id, row.id), isNull(stories.genericCommentary)),
        );
    }
    stats.updated += 1;
  }
  return stats;
}

async function backfillEvents(dryRun: boolean): Promise<BackfillStats> {
  const stats: BackfillStats = { scanned: 0, updated: 0, fellBack: 0 };
  const rows = await db
    .select({
      id: events.id,
      whyItMatters: events.whyItMatters,
      whyItMattersTemplate: events.whyItMattersTemplate,
    })
    .from(events)
    .where(isNull(events.genericCommentary));
  for (const row of rows) {
    stats.scanned += 1;
    const derived = deriveEventGenericCommentary(
      row.whyItMatters,
      row.whyItMattersTemplate,
    );
    if (!derived) continue;
    const usedFallback = !parseTierTemplate(row.whyItMattersTemplate);
    if (usedFallback) stats.fellBack += 1;
    if (!dryRun) {
      await db
        .update(events)
        .set({ genericCommentary: derived })
        .where(and(eq(events.id, row.id), isNull(events.genericCommentary)));
    }
    stats.updated += 1;
  }
  return stats;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));
  // eslint-disable-next-line no-console
  console.log(
    `[backfill-generic-commentary] table=${args.table} dryRun=${args.dryRun}`,
  );

  if (args.table === "stories" || args.table === "both") {
    const s = await backfillStories(args.dryRun);
    // eslint-disable-next-line no-console
    console.log(
      `[stories] scanned=${s.scanned} updated=${s.updated} fellBack=${s.fellBack}`,
    );
  }
  if (args.table === "events" || args.table === "both") {
    const e = await backfillEvents(args.dryRun);
    // eslint-disable-next-line no-console
    console.log(
      `[events]  scanned=${e.scanned} updated=${e.updated} fellBack=${e.fellBack}`,
    );
  }

  // Ensure the script exits cleanly. The drizzle pool will hold the
  // process open otherwise.
  const exitVoid = (): void => process.exit(0);
  // Touch sql to retain the import in lint configurations that strip
  // unused symbols — also enables drop-in extension if a future
  // backfill needs a raw query.
  void sql;
  exitVoid();
}

if (require.main === module) {
  main().catch((err) => {
    // eslint-disable-next-line no-console
    console.error("[backfill-generic-commentary] FAILED", err);
    process.exit(1);
  });
}
