import path from "node:path";
import fs from "node:fs/promises";
import {
  SCHEMA_MIGRATIONS_DDL,
  SCHEMA_MIGRATIONS_TABLE,
  lfNormalize,
  sha256Hex,
} from "../db/migrate";

// One-shot script. Reads every migration .sql under backend/src/db/migrations/,
// computes the canonical content_hash via the same code path the runner uses,
// and emits the CREATE TABLE + INSERT statements for seeding `schema_migrations`
// against a database that already has these migrations applied (dev + prod
// both have the existing 0000–N applied via the deprecated drizzle-kit
// migrator).
//
// The CREATE TABLE statement is imported from migrate.ts as the single source
// of truth for the schema definition.
//
// Output: SQL on stdout. Pipe into psql, or copy into Neon SQL editor.
//
// Lifecycle: kept through Step 5 (prod seeding), then deleted.

const MIGRATION_FILENAME_REGEX = /^\d{4}_.*\.sql$/;

async function main(): Promise<void> {
  const migrationsDir = path.join(__dirname, "..", "db", "migrations");
  const entries = await fs.readdir(migrationsDir, { withFileTypes: true });
  const filenames = entries
    .filter((e) => e.isFile() && MIGRATION_FILENAME_REGEX.test(e.name))
    .map((e) => e.name)
    .sort();

  const lines: string[] = [];
  lines.push(`-- Seed ${SCHEMA_MIGRATIONS_TABLE} from current applied state.`);
  lines.push("-- Run once, against a database where these migrations are already applied via the previous migrator.");
  lines.push("-- Generated by backend/src/scripts/seed-migration-state.ts");
  lines.push("");
  lines.push(`${SCHEMA_MIGRATIONS_DDL};`);
  lines.push("");

  for (const filename of filenames) {
    const fullPath = path.join(migrationsDir, filename);
    const buf = await fs.readFile(fullPath);
    const contents = lfNormalize(buf);
    const hash = sha256Hex(contents);
    lines.push(
      `INSERT INTO ${SCHEMA_MIGRATIONS_TABLE} (filename, content_hash, applied_by) VALUES ('${filename}', '${hash}', 'seed-migration-state') ON CONFLICT (filename) DO NOTHING;`
    );
  }

  lines.push("");
  lines.push(`-- ${filenames.length} migration row(s) emitted.`);
  process.stdout.write(lines.join("\n") + "\n");
}

main().catch((e) => {
  console.error(`[seed-migration-state] failed: ${(e as Error).message}`);
  process.exit(1);
});
